/** LaTeX 符号：分类 + 插入片段（通常为命令或数学符号） */
export type SymbolCategory = 'common' | 'greek' | 'arrows' | 'operators' | 'relations' | 'sets' | 'delims' | 'accents' | 'misc'

export type LatexSymbol = { label: string; insert: string }

export const LATEX_SYMBOL_CATEGORIES: { id: SymbolCategory; title: string; items: LatexSymbol[] }[] = [
  {
    id: 'common',
    title: '常用',
    items: [
      { label: 'α', insert: '\\alpha' },
      { label: 'β', insert: '\\beta' },
      { label: 'γ', insert: '\\gamma' },
      { label: 'θ', insert: '\\theta' },
      { label: 'λ', insert: '\\lambda' },
      { label: 'μ', insert: '\\mu' },
      { label: 'σ', insert: '\\sigma' },
      { label: 'ω', insert: '\\omega' },
      { label: 'π', insert: '\\pi' },
      { label: '∑', insert: '\\sum' },
      { label: '∏', insert: '\\prod' },
      { label: '∫', insert: '\\int' },
      { label: '∂', insert: '\\partial' },
      { label: '∞', insert: '\\infty' },
      { label: '√', insert: '\\sqrt{}' },
      { label: '·', insert: '\\cdot' },
      { label: '×', insert: '\\times' },
      { label: '÷', insert: '\\div' },
      { label: '±', insert: '\\pm' },
      { label: '≤', insert: '\\leq' },
      { label: '≥', insert: '\\geq' },
      { label: '≠', insert: '\\neq' },
      { label: '≈', insert: '\\approx' },
      { label: '→', insert: '\\rightarrow' },
      { label: '⇒', insert: '\\Rightarrow' },
      { label: '↔', insert: '\\leftrightarrow' },
      { label: '∈', insert: '\\in' },
      { label: '∉', insert: '\\notin' },
      { label: '⊂', insert: '\\subset' },
      { label: '⊆', insert: '\\subseteq' },
      { label: '∪', insert: '\\cup' },
      { label: '∩', insert: '\\cap' },
      { label: '∀', insert: '\\forall' },
      { label: '∃', insert: '\\exists' },
      { label: 'ℝ', insert: '\\mathbb{R}' },
      { label: 'ℕ', insert: '\\mathbb{N}' },
      { label: 'ℤ', insert: '\\mathbb{Z}' },
      { label: 'ℚ', insert: '\\mathbb{Q}' },
      { label: 'ℂ', insert: '\\mathbb{C}' },
      { label: '𝔼', insert: '\\mathbb{E}' },
      { label: '…', insert: '\\ldots' },
      { label: '⋯', insert: '\\cdots' },
      { label: '⋮', insert: '\\vdots' },
      { label: '⋱', insert: '\\ddots' },
      { label: 'fr', insert: '\\frac{}{}' },
      { label: '√n', insert: '\\sqrt[]{}' },
      { label: 'lim', insert: '\\lim_{}' },
      { label: 'max', insert: '\\max' },
      { label: 'min', insert: '\\min' },
      { label: 'sup', insert: '\\sup' },
      { label: 'inf', insert: '\\inf' },
      { label: 'arg', insert: '\\arg' },
      { label: 'det', insert: '\\det' },
      { label: 'dim', insert: '\\dim' },
      { label: 'ker', insert: '\\ker' },
      { label: 'deg', insert: '\\deg' },
      { label: 'gcd', insert: '\\gcd' },
      { label: 'mod', insert: '\\bmod' },
      { label: 'pmod', insert: '\\pmod{}' },
      { label: 'binom', insert: '\\binom{}{}' },
      { label: 'choose', insert: '{ \\choose }' },
      { label: 'text', insert: '\\text{}' },
      { label: 'mathrm', insert: '\\mathrm{}' },
      { label: 'mathbf', insert: '\\mathbf{}' },
      { label: 'mathit', insert: '\\mathit{}' },
      { label: 'mathcal', insert: '\\mathcal{}' },
      { label: 'mathfrak', insert: '\\mathfrak{}' },
      { label: 'operatorname', insert: '\\operatorname{}' },
      { label: 'quad', insert: '\\quad' },
      { label: 'qquad', insert: '\\qquad' },
      { label: ' ', insert: '\\,' },
      { label: ' ', insert: '\\;' },
      { label: ' ', insert: '\\quad' },
      { label: '↦', insert: '\\mapsto' },
      { label: '⊤', insert: '\\top' },
      { label: '⊥', insert: '\\bot' },
      { label: '∅', insert: '\\emptyset' },
      { label: '∇', insert: '\\nabla' },
      { label: '⟨⟩', insert: '\\langle  \\rangle' },
      { label: '‖', insert: '\\|' },
      { label: '‖‖', insert: '\\|' },
      { label: '‖·‖', insert: '\\lVert  \\rVert' },
      { label: 'exp', insert: '\\exp' },
      { label: 'log', insert: '\\log' },
      { label: 'ln', insert: '\\ln' },
      { label: 'sin', insert: '\\sin' },
      { label: 'cos', insert: '\\cos' },
      { label: 'tan', insert: '\\tan' },
      { label: 'cot', insert: '\\cot' },
      { label: 'sec', insert: '\\sec' },
      { label: 'csc', insert: '\\csc' },
      { label: 'arcsin', insert: '\\arcsin' },
      { label: 'arccos', insert: '\\arccos' },
      { label: 'arctan', insert: '\\arctan' },
      { label: 'sinh', insert: '\\sinh' },
      { label: 'cosh', insert: '\\cosh' },
      { label: 'tanh', insert: '\\tanh' },
    ],
  },
  {
    id: 'greek',
    title: '希腊字母',
    items: [
      { label: 'α', insert: '\\alpha' },
      { label: 'β', insert: '\\beta' },
      { label: 'γ', insert: '\\gamma' },
      { label: 'δ', insert: '\\delta' },
      { label: 'ε', insert: '\\varepsilon' },
      { label: 'ϵ', insert: '\\epsilon' },
      { label: 'ζ', insert: '\\zeta' },
      { label: 'η', insert: '\\eta' },
      { label: 'θ', insert: '\\theta' },
      { label: 'ϑ', insert: '\\vartheta' },
      { label: 'ι', insert: '\\iota' },
      { label: 'κ', insert: '\\kappa' },
      { label: 'λ', insert: '\\lambda' },
      { label: 'μ', insert: '\\mu' },
      { label: 'ν', insert: '\\nu' },
      { label: 'ξ', insert: '\\xi' },
      { label: 'π', insert: '\\pi' },
      { label: 'ϖ', insert: '\\varpi' },
      { label: 'ρ', insert: '\\rho' },
      { label: 'ϱ', insert: '\\varrho' },
      { label: 'σ', insert: '\\sigma' },
      { label: 'ς', insert: '\\varsigma' },
      { label: 'τ', insert: '\\tau' },
      { label: 'υ', insert: '\\upsilon' },
      { label: 'φ', insert: '\\varphi' },
      { label: 'ϕ', insert: '\\phi' },
      { label: 'χ', insert: '\\chi' },
      { label: 'ψ', insert: '\\psi' },
      { label: 'ω', insert: '\\omega' },
      { label: 'Γ', insert: '\\Gamma' },
      { label: 'Δ', insert: '\\Delta' },
      { label: 'Θ', insert: '\\Theta' },
      { label: 'Λ', insert: '\\Lambda' },
      { label: 'Ξ', insert: '\\Xi' },
      { label: 'Π', insert: '\\Pi' },
      { label: 'Σ', insert: '\\Sigma' },
      { label: 'Υ', insert: '\\Upsilon' },
      { label: 'Φ', insert: '\\Phi' },
      { label: 'Ψ', insert: '\\Psi' },
      { label: 'Ω', insert: '\\Omega' },
    ],
  },
  {
    id: 'arrows',
    title: '箭头',
    items: [
      { label: '→', insert: '\\rightarrow' },
      { label: '←', insert: '\\leftarrow' },
      { label: '↔', insert: '\\leftrightarrow' },
      { label: '⇒', insert: '\\Rightarrow' },
      { label: '⇐', insert: '\\Leftarrow' },
      { label: '⇔', insert: '\\Leftrightarrow' },
      { label: '↦', insert: '\\mapsto' },
      { label: '⟼', insert: '\\longmapsto' },
      { label: '↑', insert: '\\uparrow' },
      { label: '↓', insert: '\\downarrow' },
      { label: '↕', insert: '\\updownarrow' },
      { label: '⇑', insert: '\\Uparrow' },
      { label: '⇓', insert: '\\Downarrow' },
      { label: '⇕', insert: '\\Updownarrow' },
      { label: '⟶', insert: '\\longrightarrow' },
      { label: '⟵', insert: '\\longleftarrow' },
      { label: '⟷', insert: '\\longleftrightarrow' },
      { label: '⇗', insert: '\\nearrow' },
      { label: '⇘', insert: '\\searrow' },
      { label: '⇖', insert: '\\nwarrow' },
      { label: '⇙', insert: '\\swarrow' },
      { label: '↪', insert: '\\hookrightarrow' },
      { label: '↩', insert: '\\hookleftarrow' },
      { label: '⇝', insert: '\\rightsquigarrow' },
      { label: '↣', insert: '\\rightarrowtail' },
      { label: '↠', insert: '\\twoheadrightarrow' },
    ],
  },
  {
    id: 'operators',
    title: '运算符',
    items: [
      { label: '∑', insert: '\\sum' },
      { label: '∏', insert: '\\prod' },
      { label: '∐', insert: '\\coprod' },
      { label: '∫', insert: '\\int' },
      { label: '∬', insert: '\\iint' },
      { label: '∭', insert: '\\iiint' },
      { label: '∮', insert: '\\oint' },
      { label: '∂', insert: '\\partial' },
      { label: '∇', insert: '\\nabla' },
      { label: '∞', insert: '\\infty' },
      { label: '√', insert: '\\sqrt{}' },
      { label: '∛', insert: '\\sqrt[3]{}' },
      { label: '·', insert: '\\cdot' },
      { label: '×', insert: '\\times' },
      { label: '÷', insert: '\\div' },
      { label: '±', insert: '\\pm' },
      { label: '∓', insert: '\\mp' },
      { label: '⊕', insert: '\\oplus' },
      { label: '⊗', insert: '\\otimes' },
      { label: '⊘', insert: '\\oslash' },
      { label: '⊙', insert: '\\odot' },
      { label: '⊎', insert: '\\uplus' },
      { label: '⊔', insert: '\\sqcup' },
      { label: '⊓', insert: '\\sqcap' },
      { label: '⋆', insert: '\\star' },
      { label: '∗', insert: '\\ast' },
      { label: '∘', insert: '\\circ' },
      { label: '∙', insert: '\\bullet' },
      { label: '⋅', insert: '\\cdot' },
      { label: '†', insert: '\\dagger' },
      { label: '‡', insert: '\\ddagger' },
      { label: '♯', insert: '\\sharp' },
      { label: '♭', insert: '\\flat' },
      { label: '♮', insert: '\\natural' },
      { label: '△', insert: '\\bigtriangleup' },
      { label: '▽', insert: '\\bigtriangledown' },
      { label: '◁', insert: '\\triangleleft' },
      { label: '▷', insert: '\\triangleright' },
      { label: '⊲', insert: '\\trianglelefteq' },
      { label: '⊳', insert: '\\trianglerighteq' },
      { label: '⊴', insert: '\\unlhd' },
      { label: '⊵', insert: '\\unrhd' },
      { label: '≀', insert: '\\wr' },
      { label: '⨿', insert: '\\amalg' },
      { label: '∐', insert: '\\coprod' },
      { label: '∨', insert: '\\vee' },
      { label: '∧', insert: '\\wedge' },
      { label: '⊻', insert: '\\veebar' },
      { label: '⊼', insert: '\\barwedge' },
      { label: '⊽', insert: '\\doublebarwedge' },
    ],
  },
  {
    id: 'relations',
    title: '关系',
    items: [
      { label: '≤', insert: '\\leq' },
      { label: '≥', insert: '\\geq' },
      { label: '≦', insert: '\\leqq' },
      { label: '≧', insert: '\\geqq' },
      { label: '≪', insert: '\\ll' },
      { label: '≫', insert: '\\gg' },
      { label: '≠', insert: '\\neq' },
      { label: '≈', insert: '\\approx' },
      { label: '≃', insert: '\\simeq' },
      { label: '∼', insert: '\\sim' },
      { label: '≅', insert: '\\cong' },
      { label: '≡', insert: '\\equiv' },
      { label: '≢', insert: '\\not\\equiv' },
      { label: '∝', insert: '\\propto' },
      { label: '≺', insert: '\\prec' },
      { label: '≻', insert: '\\succ' },
      { label: '≼', insert: '\\preceq' },
      { label: '≽', insert: '\\succeq' },
      { label: '⊏', insert: '\\sqsubset' },
      { label: '⊐', insert: '\\sqsupset' },
      { label: '⊑', insert: '\\sqsubseteq' },
      { label: '⊒', insert: '\\sqsupseteq' },
      { label: '∈', insert: '\\in' },
      { label: '∉', insert: '\\notin' },
      { label: '∋', insert: '\\ni' },
      { label: '⊂', insert: '\\subset' },
      { label: '⊃', insert: '\\supset' },
      { label: '⊆', insert: '\\subseteq' },
      { label: '⊇', insert: '\\supseteq' },
      { label: '⊊', insert: '\\subsetneq' },
      { label: '⊋', insert: '\\supsetneq' },
      { label: '∪', insert: '\\cup' },
      { label: '∩', insert: '\\cap' },
      { label: '⊎', insert: '\\uplus' },
      { label: '⊔', insert: '\\sqcup' },
      { label: '⊓', insert: '\\sqcap' },
      { label: '⊥', insert: '\\perp' },
      { label: '∥', insert: '\\parallel' },
      { label: '∦', insert: '\\nparallel' },
      { label: '⊨', insert: '\\vDash' },
      { label: '⊢', insert: '\\vdash' },
      { label: '⊣', insert: '\\dashv' },
      { label: '⊩', insert: '\\Vdash' },
      { label: '⊪', insert: '\\Vvdash' },
      { label: '⊧', insert: '\\models' },
      { label: '∀', insert: '\\forall' },
      { label: '∃', insert: '\\exists' },
      { label: '∄', insert: '\\nexists' },
      { label: '∴', insert: '\\therefore' },
      { label: '∵', insert: '\\because' },
    ],
  },
  {
    id: 'sets',
    title: '集合',
    items: [
      { label: '∅', insert: '\\emptyset' },
      { label: '∅', insert: '\\varnothing' },
      { label: '℘', insert: '\\wp' },
      { label: '∖', insert: '\\setminus' },
      { label: '△', insert: '\\triangle' },
      { label: '⊕', insert: '\\oplus' },
      { label: 'ℕ', insert: '\\mathbb{N}' },
      { label: 'ℤ', insert: '\\mathbb{Z}' },
      { label: 'ℚ', insert: '\\mathbb{Q}' },
      { label: 'ℝ', insert: '\\mathbb{R}' },
      { label: 'ℂ', insert: '\\mathbb{C}' },
      { label: 'ℙ', insert: '\\mathbb{P}' },
      { label: '𝟙', insert: '\\mathbb{1}' },
      { label: '{ }', insert: '\\{  \\}' },
      { label: '∣', insert: '\\mid' },
      { label: '∤', insert: '\\nmid' },
    ],
  },
  {
    id: 'delims',
    title: '括号',
    items: [
      { label: '( )', insert: '\\left(  \\right)' },
      { label: '[ ]', insert: '\\left[  \\right]' },
      { label: '{ }', insert: '\\left\\{  \\right\\}' },
      { label: '⌊ ⌋', insert: '\\left\\lfloor  \\right\\rfloor' },
      { label: '⌈ ⌉', insert: '\\left\\lceil  \\right\\rceil' },
      { label: '⟨ ⟩', insert: '\\left\\langle  \\right\\rangle' },
      { label: '‖ ‖', insert: '\\left\\lVert  \\right\\rVert' },
      { label: '| |', insert: '\\left|  \\right|' },
      { label: '‖', insert: '\\|' },
      { label: '↑', insert: '\\uparrow' },
      { label: '↓', insert: '\\downarrow' },
      { label: '.', insert: '\\left.  \\right.' },
      { label: 'bigl', insert: '\\bigl(  \\bigr)' },
      { label: 'Bigl', insert: '\\Bigl(  \\Bigr)' },
      { label: 'biggl', insert: '\\biggl(  \\biggr)' },
      { label: 'Biggl', insert: '\\Biggl(  \\Biggr)' },
    ],
  },
  {
    id: 'accents',
    title: '重音',
    items: [
      { label: 'ˆ', insert: '\\hat{}' },
      { label: 'ˇ', insert: '\\check{}' },
      { label: '˘', insert: '\\breve{}' },
      { label: '˜', insert: '\\tilde{}' },
      { label: '˙', insert: '\\dot{}' },
      { label: '¨', insert: '\\ddot{}' },
      { label: '⃛', insert: '\\dddot{}' },
      { label: '‾', insert: '\\bar{}' },
      { label: '→⃗', insert: '\\vec{}' },
      { label: 'ˊ', insert: "\\'" },
      { label: 'ˋ', insert: '\\`' },
      { label: '˝', insert: '\\"' },
      { label: '̂', insert: '\\widehat{}' },
      { label: '̃', insert: '\\widetilde{}' },
      { label: '‾', insert: '\\overline{}' },
      { label: '‾', insert: '\\underline{}' },
      { label: '⏞', insert: '\\overbrace{}' },
      { label: '⏟', insert: '\\underbrace{}' },
    ],
  },
  {
    id: 'misc',
    title: '其它',
    items: [
      { label: '°', insert: '^\\circ' },
      { label: '′', insert: "'" },
      { label: '″', insert: "''" },
      { label: '‴', insert: "'''" },
      { label: '…', insert: '\\ldots' },
      { label: '⋯', insert: '\\cdots' },
      { label: '⋮', insert: '\\vdots' },
      { label: '⋱', insert: '\\ddots' },
      { label: 'ℓ', insert: '\\ell' },
      { label: 'ℏ', insert: '\\hbar' },
      { label: 'ℑ', insert: '\\Im' },
      { label: 'ℜ', insert: '\\Re' },
      { label: 'ℵ', insert: '\\aleph' },
      { label: 'ℶ', insert: '\\beth' },
      { label: 'ℷ', insert: '\\gimel' },
      { label: 'ℸ', insert: '\\daleth' },
      { label: '⊥', insert: '\\perp' },
      { label: '∥', insert: '\\parallel' },
      { label: '∠', insert: '\\angle' },
      { label: '♣', insert: '\\clubsuit' },
      { label: '♢', insert: '\\diamondsuit' },
      { label: '♡', insert: '\\heartsuit' },
      { label: '♠', insert: '\\spadesuit' },
      { label: '§', insert: '\\S' },
      { label: '¶', insert: '\\P' },
      { label: '©', insert: '\\copyright' },
      { label: '£', insert: '\\pounds' },
      { label: '∀', insert: '\\forall' },
      { label: '∃', insert: '\\exists' },
      { label: '∅', insert: '\\emptyset' },
      { label: '∇', insert: '\\nabla' },
      { label: '♯', insert: '\\sharp' },
      { label: '♭', insert: '\\flat' },
      { label: '♮', insert: '\\natural' },
      { label: '⌊', insert: '\\lfloor' },
      { label: '⌋', insert: '\\rfloor' },
      { label: '⌈', insert: '\\lceil' },
      { label: '⌉', insert: '\\rceil' },
      { label: '⟨', insert: '\\langle' },
      { label: '⟩', insert: '\\rangle' },
      { label: '°C', insert: '^\\circ\\mathrm{C}' },
    ],
  },
]
